// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_CzN8VDvuBI1e88WHN_fBJ57xxUZW6WQ',
    appId: '1:278558687377:web:bd48c8bc36ec964770bf30',
    messagingSenderId: '278558687377',
    projectId: 'profile-aad40',
    authDomain: 'profile-aad40.firebaseapp.com',
    storageBucket: 'profile-aad40.firebasestorage.app',
    measurementId: 'G-CV2ZH3Z130',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4B3rZoTUNfRcU8-w6YdcD455pNFo4luQ',
    appId: '1:278558687377:android:d431daba989c2b2370bf30',
    messagingSenderId: '278558687377',
    projectId: 'profile-aad40',
    storageBucket: 'profile-aad40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfdo6IxcDdmTaH1AQbbV5x2tEg0xHZ3iI',
    appId: '1:278558687377:ios:c25bc69b6d7a832770bf30',
    messagingSenderId: '278558687377',
    projectId: 'profile-aad40',
    storageBucket: 'profile-aad40.firebasestorage.app',
    iosBundleId: 'com.example.profile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_CzN8VDvuBI1e88WHN_fBJ57xxUZW6WQ',
    appId: '1:278558687377:web:76224fed1538671870bf30',
    messagingSenderId: '278558687377',
    projectId: 'profile-aad40',
    authDomain: 'profile-aad40.firebaseapp.com',
    storageBucket: 'profile-aad40.firebasestorage.app',
    measurementId: 'G-X1DSDPXBY5',
  );
}
